#!/bin/bash
#default_workspace_path="~/adamr"
default_workspace_path="./evaluation"
project_name=""
job_record=""
# read workspace from command line
read -p "Workspace path [$default_workspace_path]: " workspace_path

if [ "$workspace_path" = "" ]; then
   workspace_path=$default_workspace_path
fi



# read project name 
while [ "$project_name" = "" ] 
  do
    read -p "Project name (folder where the files stored): " project_name
  done



# read job_record name
while [ "$job_record" = "" ] 
  do
    read -p "Job-record name (e.g. demo -> Demo_Job): " job_record
  done



# create job directors
project_path=$workspace_path"/"$project_name
mkdir -p $project_path


# create job header
sed "s/^package _Job is/package "$job_record"_Job is/g" "example_configs/job.ads.template" > $project_path"/"$job_record"_job.ads.tmp"
sed "s/^end _Job;/end "$job_record"_Job;/g" $project_path"/"$job_record"_job.ads.tmp" > $project_path"/"$job_record"_job.ads"
rm $project_path"/"$job_record"_job.ads.tmp"

# create job implementation
sed "s/^package body _Job is/package body "$job_record"_Job is/g" "example_configs/job.adb.template" > $project_path"/"$job_record"_job.adb.tmp"
sed "s/^end _Job;/end "$job_record"_Job;/g" $project_path"/"$job_record"_job.adb.tmp" > $project_path"/"$job_record"_job.adb"
rm $project_path"/"$job_record"_job.adb.tmp"

# create master
sed "s/^-- insert specification for the job/with "$job_record"_Job;/g" "example_configs/master.adb.template" > $project_path"/master.adb.tmp"
sed "s/^  package Job renames _Job;/  package Job renames "$job_record"_Job;/g" $project_path"/master.adb.tmp" > $project_path"/master.adb"
rm $project_path"/master.adb.tmp"

# create mapper
sed "s/^-- insert specification for the job/with "$job_record"_Job;/g" "example_configs/mapper.adb.template" > $project_path"/mapper.adb.tmp"
sed "s/^  package Job renames _Job;/  package Job renames "$job_record"_Job;/g" $project_path"/mapper.adb.tmp" > $project_path"/mapper.adb"
rm $project_path"/mapper.adb.tmp"

# create reducer
sed "s/^-- insert specification for the job/with "$job_record"_Job;/g" "example_configs/reducer.adb.template" > $project_path"/reducer.adb.tmp"
sed "s/^  package Job renames _Job;/  package Job renames "$job_record"_Job;/g" $project_path"/reducer.adb.tmp" > $project_path"/reducer.adb"
rm $project_path"/reducer.adb.tmp"

# create Makefile
cp "example_configs/Makefile.template" $project_path"/Makefile"