------------------------------------------------------------------------------
--                                                                          --
--      JR-ADA-Tools - Ada 95 general Development Framework and Tools       --
--                                                                          --
--             Copyright (C) 2002, Jerome Raffalli                          --
--                                                                          --
--   This package is a free adaptation of GtkAda's Glib.XML                 --
--     Copyright (C) Emmanuel Briot, Joel Brobecker and Arnaud Charlet      --
--                                                                          --
-- This is free software;  you can  redistribute it  and/or modify it under --
-- terms of the  GNU General Public License as published  by the Free Soft- --
-- ware  Foundation;  either version 2,  or (at your option) any later ver- --
-- sion. It is distributed in the hope that it will be useful,  but WITHOUT --
-- ANY WARRANTY;  without  even the  implied warranty of MERCHANTABILITY or --
-- FITNESS FOR A PARTICULAR PURPOSE.    See the GNU General  Public License --
-- for  more details.  You should have  received  a copy of the GNU General --
-- Public License  distributed with this;  see file COPYING.  If not, write --
-- to  the Free Software Foundation,  59 Temple Place - Suite 330,  Boston, --
-- MA 02111-1307, USA.                                                      --
--                                                                          --
-- As a special exception,  if other files  instantiate  generics from this --
-- unit, or you link  this unit with other files  to produce an executable, --
-- this  unit  does not  by itself cause  the resulting  executable  to  be --
-- covered  by the  GNU  General  Public  License.  This exception does not --
-- however invalidate  any other reasons why  the executable file  might be --
-- covered by the  GNU Public License.                                      --
--                                                                          --
------------------------------------------------------------------------------

-- <SUMMARY> -----------------------------------------------------------------
-- Narrow_XML is the String version of XML Parser and Writer
-- Wide_XML is the Wide_String version of XML Parser and Writer
--
-- <DESCRIPTION> -------------------------------------------------------------
-- Put here all informations about usage of the package
--
-- <DEVELOPMENT> -------------------------------------------------------------
--   Public revision : 1.0
--   $Id: jio-Ada_Mr.Xml.ads,v 1.1 2003/01/13 12:12:05 jerome Exp $
--   Notes :
------------------------------------------------------------------------------
package Simple_Xml is
end Simple_Xml;
