#!/bin/bash
#/usr/local/ada-4.3/bin/gnatmake -I../mapper -I../lib mr_mapper_count_char.adb && rm *.ali && rm *.o
gnatmake -I../mapper -I../lib mr_mapper_count_char.adb -largs -L/Developer/SDKs/MacOSX10.5.sdk/usr/lib -mmacosx-version-min=10.5.0 -shared-libgcc
rm *.o *.ali